-- 添加用户信息表
-- 用于存储 AI 记住的个人信息
CREATE TABLE IF NOT EXISTS user_info (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID, -- 可选：登录用户关联
  device_id VARCHAR(64), -- 可选：游客设备关联
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

  -- 确保一个用户/设备只有一条记录
  UNIQUE (user_id, device_id)
);

-- 添加 AI 记忆表
-- 用于存储对话历史和 AI 记忆
CREATE TABLE IF NOT EXISTS ai_memory (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID, -- 可选：登录用户关联
  device_id VARCHAR(64), -- 可选：游客设备关联
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

  -- 确保一个用户/设备只有一条记录
  UNIQUE (user_id, device_id)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_user_info_user ON user_info(user_id);
CREATE INDEX IF NOT EXISTS idx_user_info_device ON user_info(device_id);
CREATE INDEX IF NOT EXISTS idx_ai_memory_user ON ai_memory(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_memory_device ON ai_memory(device_id);

-- 添加注释
COMMENT ON TABLE user_info IS '用户信息表 - AI 记住的个人信息';
COMMENT ON TABLE ai_memory IS 'AI 记忆表 - 对话历史和用户习惯';

COMMENT ON COLUMN user_info.user_id IS '登录用户 ID（可选）';
COMMENT ON COLUMN user_info.device_id IS '游客设备 ID（可选）';
COMMENT ON COLUMN user_info.content IS '用户信息内容（Markdown 格式）';

COMMENT ON COLUMN ai_memory.user_id IS '登录用户 ID（可选）';
COMMENT ON COLUMN ai_memory.device_id IS '游客设备 ID（可选）';
COMMENT ON COLUMN ai_memory.content IS 'AI 记忆内容（Markdown 格式）';
